### ISSUE TITLE
Spinning loading indicator

### ISSUE THREAD

**Issue by pokey** [paul-schaaf/talon-filetree#8]
![brokenFileTree](https://user-images.githubusercontent.com/755842/232252742-b7640998-aeea-4f36-87bd-2bb565c05097.gif)

While this is happening, clicking on any item to expand it doesn't work.  I wonder if #3 would help here 🤔

This occurs on window reload, and does eventually resolve, but takes nearly a minute

**Comment by paul-schaaf** [comment]
1. is this a repo that I could have a look at by any chance?
2. so this very long loading time only happens on startup and afterwards it doesn't?

3. could you check whether this still occurs on version `0.5.6` that I just released? turns out the library I was using did a lot of unnecessary file watches on startup that I have now removed.

**Comment by pokey** [comment]
Repo was https://github.com/cursorless-dev/cursorless.  But I just checked in `0.5.6` and it's now working great!
